services:
  ctfconsole_frontend:
    profiles: 
    - "ctfconsole"
    - "frontend"
    build: frontend
    image: ctfconsole_frontend:latest
    container_name: ctfconsole_frontend
    hostname: ctfconsole_frontend
    env_file: .env
    ports:
      - "${CTFCONSOLE_FRONTEND_PORT}:${CTFCONSOLE_FRONTEND_PORT}"
  ctfconsole_backend:
    profiles: 
    - "ctfconsole"
    - "backend"
    build: backend
    image: ctfconsole_backend:latest
    container_name: ctfconsole_backend
    hostname: ctfconsole_backend
    env_file: .env
    volumes:
      - ctfconsole_logs:/var/log/ctfconsole/
      - ctfconsole_db:/opt/ctfconsole/backend/storage
    ports:
      - "${CTFCONSOLE_BACKEND_PORT}:${CTFCONSOLE_BACKEND_PORT}"

volumes:
  ctfconsole_db:
    name: ctfconsole_db
  ctfconsole_logs:
    name: ctfconsole_logs