services:
  database:
    profiles: 
    - ctfconsole
    - ctfconsole_database
    build: database
    image: ctfconsole_database:${VERSION}
    container_name: ctfconsole_database
    hostname: ${POSTGRES_HOST}
    env_file:
      - .env
    volumes:
      - ctfconsole_data:${POSTGRES_LOG_PATH}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ctfconsole_database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      start_period: 5s
      timeout: 3s
      retries: 2
      interval: 5s
  backend:
    profiles: 
      - ctfconsole
      - ctfconsole_backend
    build: backend
    image: ctfconsole_backend:${VERSION}
    container_name: ctfconsole_backend
    hostname: ${CTFCONSOLE_API_HOST}
    env_file:
      - .env
    volumes:
      - ctfconsole_data:/var/log/ctfconsole/
      - ctfconsole_data:/opt/ctfconsole/database
    ports:
      - ${CTFCONSOLE_API_PORT}:${CTFCONSOLE_API_PORT}
    networks:
      - ctfconsole_database
      - ctfconsole_frontend
    depends_on:
      database:
        condition: service_healthy
  frontend:
    profiles: 
      - ctfconsole
      - ctfconsole_frontend
    build: frontend
    image: ctfconsole_frontend:${VERSION}
    container_name: ctfconsole_frontend
    hostname: ${CTFCONSOLE_UI_HOST}
    env_file:
      - .env
    environment:
      - PORT=${CTFCONSOLE_UI_PORT}
    volumes:
      - ./frontend/src:/opt/ctfconsole/src
      - ./frontend/public:/opt/ctfconsole/public
    ports:
      - ${CTFCONSOLE_UI_PORT}:${CTFCONSOLE_UI_PORT}
    networks:
      - ctfconsole_frontend

volumes:
  ctfconsole_data:
    name: ctfconsole_data

networks:
  ctfconsole_database:
  ctfconsole_frontend: