services:
  ctfconsole_db:
    profiles: 
    - ctfconsole
    - ctfconsole_db
    build: database
    image: ctfconsole_db:latest
    container_name: ctfconsole_db
    hostname: ctfconsole_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${CTFCONSOLE_DB_NAME}
      - POSTGRES_USER=${CTFCONSOLE_DB_USER}
      - POSTGRES_PASSWORD=${CTFCONSOLE_DB_PASSWORD}
    volumes:
      - ctfconsole_logs:/var/log/ctfconsole/
      - ctfconsole_db:/opt/ctfconsole/database
    ports:
      - ${CTFCONSOLE_DB_PORT}:${CTFCONSOLE_DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${CTFCONSOLE_DB_NAME} -U ${CTFCONSOLE_DB_USER}"]
      start_period: 5s
      timeout: 3s
      retries: 2
      interval: 5s
  ctfconsole_api:
    profiles: 
      - ctfconsole
      - ctfconsole_api
    build: backend
    image: ctfconsole_api:latest
    container_name: ctfconsole_api
    hostname: ctfconsole_api
    env_file:
      - .env
    volumes:
      - ctfconsole_logs:/var/log/ctfconsole/
      - ctfconsole_db:/opt/ctfconsole/database
    ports:
      - ${CTFCONSOLE_API_PORT}:${CTFCONSOLE_API_PORT}
    depends_on:
      ctfconsole_db:
        condition: service_healthy
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "CTFCONSOLE_API_HEALTHCHECK_ENDPOINT"]
  #   timeout: 3s
  #   retries: 2
  #   interval: 10s
  ctfconsole_ui:
    profiles: 
      - ctfconsole
      - ctfconsole_ui
    build: frontend
    image: ctfconsole_ui:latest
    container_name: ctfconsole_ui
    hostname: ctfconsole_ui
    environment:
      - PORT=${CTFCONSOLE_UI_PORT}
    volumes:
      - ./frontend/src:/opt/ctfconsole/src
      - ./frontend/public:/opt/ctfconsole/public
    ports:
      - ${CTFCONSOLE_UI_PORT}:${CTFCONSOLE_UI_PORT}
  # depends_on:
  #   ctfconsole_api:
  #     condition: service_healthy

volumes:
  ctfconsole_db:
    name: ctfconsole_db
  ctfconsole_logs:
    name: ctfconsole_logs