services:
  ctfconsole_frontend:
    profiles: 
      - "ctfconsole"
      - "frontend"
    build: frontend
    image: ctfconsole_frontend:latest
    container_name: ctfconsole_frontend
    hostname: ctfconsole_frontend
    environment:
      - PORT=${CTFCONSOLE_UI_PORT}
    ports:
      - ${CTFCONSOLE_UI_PORT}:${CTFCONSOLE_UI_PORT}
  ctfconsole_backend:
    profiles: 
    - "ctfconsole"
    - "backend"
    build: backend
    image: ctfconsole_backend:latest
    container_name: ctfconsole_backend
    hostname: ctfconsole_backend
    volumes:
      - ctfconsole_logs:/var/log/ctfconsole/
      - ctfconsole_db:/opt/ctfconsole/backend/storage
    ports:
      - "${CTFCONSOLE_API_PORT}:${CTFCONSOLE_API_PORT}"

volumes:
  ctfconsole_db:
    name: ctfconsole_db
  ctfconsole_logs:
    name: ctfconsole_logs