uiIp: localhost
ui: 443
apiIp: localhost
apiPort: 8443
storeDriver: sqlite3
storeName: ctfconsole
storeIp: localhost
storePort: 5432
storeCredentials:
  username: postgres
  password: postgres
logFilePath: "/var/log/ctfconsole/ctfconsole.log"